removed .DS_Store files and added in .gitignore, changed images locat…
lerubiof/redis-spring pull request #1
Opened 2024-02-25 04:25 UTC by lerubiof

…ion, changes in redis ports docker-files, changes in readme file

2024-02-26 17:52 UTC, MarciaPaez commented on README.md
> +![captura de postman donde se realiza la cracion de un usuario](https://github.com/lerubiof/redis-spring/blob/main/images/Screenshot%201.png)
Buenas! podes revisar las urls de las imagenes porque no las puedo ver bien? Gracias!

2024-02-26 17:52 UTC, MarciaPaez commented on README.md
> +## Documentación
Hay urls que tiran error 404, fijate si es un typo y corregilo. Gracias

2024-02-26 21:18 UTC, MarciaPaez commented on README.md
> +![captura de postman donde se realiza la cracion de un usuario](https://github.com/lerubiof/repos-images/blob/main/redis-spring/Screenshot%201.png)
Esto no fue lo pedido, la idea no es tomar las imagenes de otro repo. La idea es actualizar la referencia de manera que la imagen se vea correctamente. Ahora se ve asi... 
![image](https://github.com/lerubiof/redis-spring/assets/25184416/be56b579-1eef-459d-ac82-27168e801dd4)

2024-02-26 21:19 UTC, MarciaPaez commented on README.md
>  https://www.ibm.com/mx-es/topics/Java-Spring-boot
Revisa las urls porque sigo viendo el 404 en algunas y en otras directamente me redirecciona a otra parte del sitios.

2024-02-27 14:45 UTC, MarciaPaez reviewed
Agregue mas cositas, saludos!

2024-02-27 14:45 UTC, MarciaPaez commented on README.md
> +docker network create red
Formatealo como codigo, sino parece una linea comun y queremos que se destaque como un comando.

2024-02-27 14:45 UTC, MarciaPaez commented on README.md
> +docker-compose up -d
Formatealo como codigo, sino parece una linea comun y queremos que se destaque como un comando.

2024-02-27 14:45 UTC, MarciaPaez commented on README.md
> +docker excec –it Redis-Spring-Redis-1 bash
Formatealo como codigo, sino parece una linea comun y queremos que se destaque como un comando. Ademas corregi este comando porque asi no funciona.

2024-02-27 14:45 UTC, MarciaPaez commented on README.md
> +Redis-cli
Esto es correcto?

2024-03-01 00:37 UTC, lerubiof commented
se agregaron los acentos faltantes en el readme

2024-03-01 13:23 UTC, MarciaPaez requested changes
Dejé un ultimo comentario.

2024-03-01 13:23 UTC, MarciaPaez commented on README.md
> +docker excec –it redis-spring-redis-1 bash
Este comando esta mal. En lugar de excec deberia decir exec.

2024-03-01 15:01 UTC, lerubiof commented on README.md
> +docker excec –it redis-spring-redis-1 bash
listo

2024-03-01 15:27 UTC, MarciaPaez approved these changes

2024-03-01 15:58 UTC, merged